// Prestamist - API Configuration
var API='https://prestamist.optecnology.com/api/index.php?route=';
var tok=null,user=null,cls=[],mds=[],cgs=[];

function gt(){return tok||localStorage.getItem('prestamist_token');}

function x(m,r,d,cb){
    var x=new XMLHttpRequest();
    x.open(m,API+r,true);
    x.setRequestHeader('Content-Type','application/json');
    var t=gt();if(t)x.setRequestHeader('Authorization','Bearer '+t);
    x.onreadystatechange=function(){
        if(x.readyState!==4)return;
        try{var j=JSON.parse(x.responseText)}catch(e){j={error:'Invalid'}}
        if(x.status>=200&&x.status<300&&j.data!==undefined)cb(null,j.data);
        else cb(j.error||'Err '+x.status,null);
    };
    x.send(d?JSON.stringify(d):null);
}
function g(r,cb){x('GET',r,null,cb);}
function p(r,d,cb){x('POST',r,d,cb);}
function fm(n){if(n===null||n===undefined)return'0.00';var f=parseFloat(n);return f.toLocaleString('en-US',{minimumFractionDigits:2,maximumFractionDigits:2});}function fms(n){var s=typeof _moneda_simbolo!=='undefined'?_moneda_simbolo:'RD$';return s+' '+fm(n);}function formatMonInput(el){if(!el)return;var v=el.value.replace(/[^\d.]/g,'');var partes=v.split('.');if(partes.length>2)v=partes[0]+'.'+partes[1];el.value=v;el.dataset.valor=v;}function monInputLive(el){if(!el)return;var v=el.value.replace(/[^\d.]/g,'');var partes=v.split('.');if(partes.length>2)v=partes[0]+'.'+partes[1];el.value=v;el.dataset.valor=v;}function monInputBlur(el){if(!el)return;var v=el.dataset.valor||el.value.replace(/[^\d.]/g,'');var num=parseFloat(v);if(!isNaN(num)&&v){el.value=num.toLocaleString('en-US',{minimumFractionDigits:2,maximumFractionDigits:2});}else{el.value='';}}function getMonVal(el){if(!el)return 0;if(el.dataset&&el.dataset.valor)return parseFloat(el.dataset.valor)||0;return parseFloat(el.value.replace(/[^\d.]/g,''))||0;}

// Internationalization
var LANG={
    es:{
        name:'Espa\u00F1ol',flag:'\uD83C\uDDEA\uD83C\uDDF8',login:'Iniciar Sesion',dashboard:'Dashboard',prestamos:'Prestamos',registro:'Registro',historial:'Historial',clientes:'Clientes',monedas:'Monedas',configuracion:'Configuracion',usuarios:'Usuarios',preferencias:'Preferencias',perfil:'Perfil',cerrar:'Cerrar Sesion',cerrar_modal:'Cerrar',nuevo:'Nuevo',editar:'Editar',eliminar:'Eliminar',guardar:'Guardar',cancelar:'Cancelar',buscar:'Buscar',limpiar:'Limpiar',fecha:'Fecha',monto:'Monto',pagado:'Pagado',cuotas:'Cuotas',interes:'Interes',estado:'Estado',cliente:'Cliente',moneda:'Moneda',tipo_cuota:'Tipo Cuota',cargo:'Cargo',nombre:'Nombre',apellido:'Apellido',documento:'Documento',telefono:'Telefono',email:'Email',direccion:'Direccion',login:'Login',clave:'Clave',usuario:'Usuario',tema:'Tema',idioma:'Idioma',pagar:'Pagar',comprobante:'Comprobante',imprimir:'Imprimir',recibo:'Recibo',monto_total:'Monto Total',valor_cuota:'Valor Cuota',total_pagado:'Total Pagado',restante:'Restante',cuota:'Cuota',fecha_pago:'Fecha Pago',mora:'Mora',sin_datos:'Sin datos',completar:'Complete todos los campos',error:'Error',exito:'Exito',activo:'Activo',inactivo:'Inactivo',accion:'Accion',saldo_pendiente:'Saldo Pendiente',cancelar_modal:'Cancelar',confirmar:'Confirmar',creado:'creado',actualizado:'actualizado',eliminado:'eliminado',desactivado:'desactivado',activado:'activado',desactivar:'Desactivar',activar:'Activar',cambiar_clave:'Cambiar Clave',nueva_clave:'Nueva Clave',cliente_creado:'Cliente creado correctamente',cliente_actualizado:'Cliente actualizado correctamente',prestamo_creado:'Prestamo creado correctamente',pago_realizado:'Pago realizado correctamente',moneda_creada:'Moneda creada correctamente',moneda_actualizada:'Moneda actualizada correctamente',moneda_eliminada:'Moneda eliminada correctamente',usuario_creado:'Usuario creado correctamente',usuario_actualizado:'Usuario actualizado correctamente',usuario_desactivado:'Usuario desactivado correctamente',usuario_activado:'Usuario activado correctamente',clave_actualizada:'Clave actualizada correctamente',pago_cuotas:'Pago de Cuotas',pagar_total:'Pagar Total',monto_pagar:'Monto a Pagar',seleccionadas:'cuota(s) seleccionada(s)',prestamo:'Prestamo',todos:'Todos',mostrando:'Mostrando',de:'de'
    ,contabilidad:'Contabilidad',plan_cuentas:'Plan de Cuentas',asientos_contables:'Asientos Contables',config_contable:'Config. Contable',reportes_contables:'Reportes Contables',nueva_cuenta:'Nueva Cuenta',cuenta:'Cuenta',codigo:'Código',naturaleza:'Naturaleza',nivel:'Nivel',cuenta_padre:'Cuenta Padre',nuevo_asiento:'Nuevo Asiento',agregar_linea:'Agregar Línea',cuenta_contable:'Cuenta Contable',totales:'Totales',diferencia:'Diferencia',concepto:'Concepto',operacion:'Operación',cuenta_debe:'Cuenta Débito',cuenta_haber:'Cuenta Crédito',balance_comprobacion:'Balance de Comprobación',libro_diario:'Libro Diario',libro_mayor:'Libro Mayor',estado_resultados:'Estado de Resultados',balance_general:'Balance General',config_info:'Configure las cuentas contables para cada operación.',asiento:'Asiento',detalles:'Detalles',modulo:'Módulo'},
    en:{
        name:'English',flag:'\uD83C\uDDEC\uD83C\uDDE7',login:'Sign In',dashboard:'Dashboard',prestamos:'Loans',registro:'Register',historial:'History',clientes:'Clients',monedas:'Currencies',configuracion:'Configuration',usuarios:'Users',preferencias:'Preferences',perfil:'Profile',cerrar:'Sign Out',cerrar_modal:'Close',nuevo:'New',editar:'Edit',eliminar:'Delete',guardar:'Save',cancelar:'Cancel',buscar:'Search',limpiar:'Clear',fecha:'Date',monto:'Amount',pagado:'Paid',cuotas:'Installments',interes:'Interest',estado:'Status',cliente:'Client',moneda:'Currency',tipo_cuota:'Installment Type',cargo:'Role',nombre:'Name',apellido:'Last Name',documento:'Document',telefono:'Phone',email:'Email',direccion:'Address',login:'Login',clave:'Password',usuario:'User',tema:'Theme',idioma:'Language',pagar:'Pay',comprobante:'Voucher',imprimir:'Print',recibo:'Receipt',monto_total:'Total Amount',valor_cuota:'Installment Value',total_pagado:'Total Paid',restante:'Remaining',cuota:'Installment',fecha_pago:'Payment Date',mora:'Late Fee',sin_datos:'No data',completar:'Complete fields',error:'Error',exito:'Success',activo:'Active',inactivo:'Inactive',accion:'Action',saldo_pendiente:'Pending Balance',cancelar_modal:'Cancel',confirmar:'Confirm',creado:'created',actualizado:'updated',eliminado:'deleted',desactivado:'disabled',activado:'enabled',desactivar:'Disable',activar:'Enable',cambiar_clave:'Change Password',nueva_clave:'New Password',cliente_creado:'Client created',cliente_actualizado:'Client updated',prestamo_creado:'Loan created',pago_realizado:'Payment successful',moneda_creada:'Currency created',moneda_actualizada:'Currency updated',moneda_eliminada:'Currency deleted',usuario_creado:'User created',usuario_actualizado:'User updated',usuario_desactivado:'User disabled',usuario_activado:'User enabled',clave_actualizada:'Password updated',pago_cuotas:'Payment',pagar_total:'Pay Total',monto_pagar:'Amount to Pay',seleccionadas:'installment(s) selected',prestamo:'Loan',todos:'All',mostrando:'Showing',de:'of'
    ,contabilidad:'Accounting',plan_cuentas:'Chart of Accounts',asientos_contables:'Journal Entries',config_contable:'Accounting Config',reportes_contables:'Accounting Reports',nueva_cuenta:'New Account',cuenta:'Account',codigo:'Code',naturaleza:'Nature',nivel:'Level',cuenta_padre:'Parent Account',nuevo_asiento:'New Entry',agregar_linea:'Add Line',cuenta_contable:'Account',totales:'Totals',diferencia:'Difference',concepto:'Concept',operacion:'Operation',cuenta_debe:'Debit Account',cuenta_haber:'Credit Account',balance_comprobacion:'Trial Balance',libro_diario:'General Journal',libro_mayor:'General Ledger',estado_resultados:'Income Statement',balance_general:'Balance Sheet',config_info:'Configure accounts for each operation.',asiento:'Entry',detalles:'Details',modulo:'Module'},
    fr:{
        name:'Francais',flag:'\uD83C\uDDEB\uD83C\uDDF7',login:'Connexion',dashboard:'Tableau de Bord',prestamos:'Prets',registro:'Enregistrement',historial:'Historique',clientes:'Clients',monedas:'Monnaies',configuracion:'Configuration',usuarios:'Utilisateurs',preferencias:'Preferences',perfil:'Profil',cerrar:'Deconnexion',cerrar_modal:'Fermer',nuevo:'Nouveau',editar:'Modifier',eliminar:'Supprimer',guardar:'Enregistrer',cancelar:'Annuler',buscar:'Rechercher',limpiar:'Effacer',fecha:'Date',monto:'Montant',pagado:'Pay\u00E9',cuotas:'Echeances',interes:'Interet',estado:'Statut',cliente:'Client',moneda:'Monnaie',tipo_cuota:"Type d'\u00E9ch\u00E9ance",cargo:'Role',nombre:'Nom',apellido:'Prenom',documento:'Document',telefono:'Telephone',email:'Email',direccion:'Adresse',login:'Login',clave:'Mot de passe',usuario:'Utilisateur',tema:'Theme',idioma:'Langue',pagar:'Payer',comprobante:'Recu',imprimir:'Imprimer',recibo:'Recu',monto_total:'Montant Total',valor_cuota:'Valeur Echeance',total_pagado:'Total Pay\u00E9',restante:'Restant',cuota:'Echeance',fecha_pago:'Date Paiement',mora:'P\u00E9nalit\u00E9',sin_datos:'Aucune donnee',completar:'Completez les champs',error:'Erreur',exito:'Succes',activo:'Actif',inactivo:'Inactif',accion:'Action',saldo_pendiente:'Solde Restant',cancelar_modal:'Annuler',confirmar:'Confirmer',creado:'cree',actualizado:'mis a jour',eliminado:'supprime',desactivado:'desactive',activado:'active',desactivar:'Desactiver',activar:'Activer',cambiar_clave:'Changer Mot de Passe',nueva_clave:'Nouveau Mot de Passe',cliente_creado:'Client cree',cliente_actualizado:'Client mis a jour',prestamo_creado:'Pret cree',pago_realizado:'Paiement reussi',moneda_creada:'Monnaie creee',moneda_actualizada:'Monnaie mise a jour',moneda_eliminada:'Monnaie supprimee',usuario_creado:'Utilisateur cree',usuario_actualizado:'Utilisateur mis a jour',usuario_desactivado:'Utilisateur desactive',usuario_activado:'Utilisateur active',clave_actualizada:'Mot de passe mis a jour',pago_cuotas:'Paiement',pagar_total:'Payer Total',monto_pagar:'Montant \u00E0 Payer',seleccionadas:"\u00E9ch\u00E9ance(s) s\u00E9lectionn\u00E9e(s)",prestamo:'Pret',todos:'Tous',mostrando:'Affichage',de:'sur'
    ,contabilidad:'Comptabilité',plan_cuentas:'Plan Comptable',asientos_contables:'Écritures',config_contable:'Config. Comptable',reportes_contables:'Rapports',nueva_cuenta:'Nouveau Compte',cuenta:'Compte',codigo:'Code',naturaleza:'Nature',nivel:'Niveau',cuenta_padre:'Compte Parent',nuevo_asiento:'Nouvelle Écriture',agregar_linea:'Ajouter Ligne',cuenta_contable:'Compte',totales:'Totaux',diferencia:'Différence',concepto:'Concept',operacion:'Opération',cuenta_debe:'Compte Débit',cuenta_haber:'Compte Crédit',balance_comprobacion:'Balance de Vérification',libro_diario:'Journal Général',libro_mayor:'Grand Livre',estado_resultados:'Compte de Résultat',balance_general:'Bilan',config_info:'Configurez les comptes pour chaque opération.',asiento:'Écriture',detalles:'Détails',modulo:'Module'},
    pt:{
        name:'Portugues',flag:'\uD83C\uDDE7\uD83C\uDDF7',login:'Fazer Login',dashboard:'Dashboard',prestamos:'Emprestimos',registro:'Registro',historial:'Historico',clientes:'Clientes',monedas:'Moedas',configuracion:'Configuracao',usuarios:'Usuarios',preferencias:'Preferencias',perfil:'Perfil',cerrar:'Sair',cerrar_modal:'Fechar',nuevo:'Novo',editar:'Editar',eliminar:'Excluir',guardar:'Salvar',cancelar:'Cancelar',buscar:'Buscar',limpiar:'Limpar',fecha:'Data',monto:'Valor',pagado:'Pago',cuotas:'Parcelas',interes:'Juros',estado:'Status',cliente:'Cliente',moneda:'Moeda',tipo_cuota:'Tipo de Parcela',cargo:'Cargo',nombre:'Nome',apellido:'Sobrenome',documento:'Documento',telefono:'Telefone',email:'Email',direccion:'Endereco',login:'Login',clave:'Senha',usuario:'Usuario',tema:'Tema',idioma:'Idioma',pagar:'Pagar',comprobante:'Comprovante',imprimir:'Imprimir',recibo:'Recibo',monto_total:'Valor Total',valor_cuota:'Valor Parcela',total_pagado:'Total Pago',restante:'Restante',cuota:'Parcela',fecha_pago:'Data Pagamento',mora:'Multa',sin_datos:'Sem dados',completar:'Preencha todos os campos',error:'Erro',exito:'Sucesso',activo:'Ativo',inactivo:'Inativo',accion:'Acao',saldo_pendente:'Saldo Pendente',cancelar_modal:'Cancelar',confirmar:'Confirmar',creado:'criado',actualizado:'atualizado',eliminado:'excluido',desactivado:'desativado',activado:'ativado',desactivar:'Desativar',activar:'Ativar',cambiar_clave:'Alterar Senha',nueva_clave:'Nova Senha',cliente_creado:'Cliente criado',cliente_actualizado:'Cliente atualizado',prestamo_creado:'Emprestimo criado',pago_realizado:'Pagamento realizado',moneda_creada:'Moeda criada',moneda_actualizada:'Moeda atualizada',moneda_eliminada:'Moeda excluida',usuario_creado:'Usuario criado',usuario_actualizado:'Usuario atualizado',usuario_desactivado:'Usuario desativado',usuario_activado:'Usuario ativado',clave_actualizada:'Senha atualizada',pago_cuotas:'Pagamento',pagar_total:'Pagar Total',monto_pagar:'Valor a Pagar',seleccionadas:'parcela(s) selecionada(s)',prestamo:'Emprestimo',todos:'Todos',mostrando:'Mostrando',de:'de'
    ,modulo:'Modulo',contabilidad:'Contabilidade',plan_cuentas:'Plano de Contas',asientos_contables:'Lancamentos',config_contable:'Config. Contabil',reportes_contables:'Relatorios',nueva_cuenta:'Nova Conta',codigo:'Codigo',naturaleza:'Natureza',nivel:'Nivel',cuenta_padre:'Conta Pai',nuevo_asiento:'Novo Lancamento',agregar_linea:'Adicionar Linha',cuenta_contable:'Conta Contabil',totales:'Totais',diferencia:'Diferenca',concepto:'Conceito',operacion:'Operacao',cuenta_debe:'Conta Debito',cuenta_haber:'Conta Credito',balance_comprobacion:'Balancete',libro_diario:'Diario',libro_mayor:'Razao',estado_resultados:'Resultado',balance_general:'Balanco',config_info:'Configure as contas para cada operacao.',asiento:'Lancamento',detalles:'Detalhes'}
}


function __(k){var l=L||'en';return(LANG[l]&&LANG[l][k])||LANG.en[k]||k;}

function aplicarIdioma(){if(!L||L==='undefined'){var li=localStorage.getItem('idioma');if(li)L=li;}
    var els=document.querySelectorAll('[data-i18n]');
    for(var i=0;i<els.length;i++){
        var k=els[i].getAttribute('data-i18n');
        els[i].textContent=__(k);
    }
    // Dynamic page titles
    var pg=document.querySelector('.pg.act');
    if(pg)document.getElementById('pt').textContent=__(pg.id.replace('p-',''));
if(L)localStorage.setItem('idioma',L);}

function cargarIdiomaGlobal(){
    if(!user)return;
    try{
        var prefs=JSON.parse(user.preferencias||'{}');
        if(prefs.idioma)L=prefs.idioma;
    }catch(e){}
}
var L='es';


